openapi: 3.0.1
info:
  title: TodoApp API
  description: TodoApp Backend API written in JavaScript
  version: 1.0.0

servers:
  - url: https://todo-app-backend-azure-eight.vercel.app

paths:
  /api/v1/health-check:
    get:
      tags:
        - Health Check
      responses:
        "200":
          description: OK
        "500":
          description: INTERNAL SERVER ERROR

  /api/v1/user/register:
    post:
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "anmol"
                email:
                  type: string
                  example: "me@gmail.com"
                password:
                  type: string
                  example: helloworld
      responses:
        "201":
          description: CREATED
        "400":
          description: USER ALREADY EXISTS
        "500":
          description: INTERNAL SERVER ERROR
