openapi: 3.0.1
info:
  title: TodoApp API
  description: TodoApp Backend API written in JavaScript
  version: 1.0.0

servers:
  - url: https://todoapp-backend-xn6h.onrender.com

paths:
  /api/v1/health-check:
    get:
      tags:
        - Health Check
      responses:
        "200":
          description: OK
        "500":
          description: INTERNAL SERVER ERROR

  /api/v1/user/register:
    post:
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "testMe"
                email:
                  type: string
                  example: "me@gmail.com"
                password:
                  type: string
                  example: helloworld
      responses:
        "201":
          description: CREATED
        "404":
          description: FIELDS ARE MISSING
        "400":
          description: USER ALREADY EXIST
        "500":
          description: INTERNAL SERVER ERROR
  
  /api/v1/user/login:
    post:
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "me@gmail.com"
                password:
                  type: string
                  example: helloworld
      responses:
        "200":
          description: LOGGED IN
        "404":
          description: USER NOT FOUND
        "400":
          description: FIELDS ARE MISSING
        "401":
          description: INCORRECT PASSWORD
        "500":
          description: INTERNAL SERVER ERROR / TOKEN GENERATION FAILED